---
# tasks file for mysql-server
- name: install MySQL 
  yum: name=mysql-server state=present
  when: ansible_distribution in ("CentOS", "RedHat", "Amazon")
  environment: proxy_env

- name: install MySQL on Debian derived OSes
  apt: name=mysql-server state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  environment: proxy_env

- name: ensure MySQL starts on boot
  service: name=mysqld enabled=yes state=started

- name: install MySQL python module
  yum: name=MySQL-python state=installed
  when: ansible_distribution in ("CentOS", "RedHat", "Amazon")
  environment: proxy_env

- name: install MySQL python module  on Debian derived OSes
  apt: name=python-mysqldb state=installed
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  environment: proxy_env

- name: lock down root user
  mysql_user:
    check_implicit_admin=yes
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    name="{{mysql_root_user}}"
    password="{{mysql_root_password}}"
    host="{{item}}"
    priv="*.*:ALL,GRANT"
  with_items:
    - "localhost"
    - "{{ansible_default_ipv4.address}}"
    - "{{ansible_fqdn}}"
    - "{{ansible_hostname}}"

- name: lock down root user to cluster nodes
  mysql_user:
    check_implicit_admin=yes
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    name="{{mysql_root_user}}"
    password="{{mysql_root_password}}"
    host="{{hostvars[item].ansible_default_ipv4.address}}"
    priv="*.*:ALL,GRANT"
  with_items:
    - '{{groups["cluster"]}}'

- name: lock down root user to cluster nodes
  mysql_user:
    check_implicit_admin=yes
    login_user="{{mysql_root_user}}"
    login_password="{{mysql_root_password}}"
    name="{{mysql_root_user}}"
    password="{{mysql_root_password}}"
    host="{{hostvars[item].ansible_hostname}}"
    priv="*.*:ALL,GRANT"
  with_items:
    - '{{groups["cluster"]}}'
